//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlanner
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    public partial class bd_easyplannerEntities : DbContext
    {
        public bd_easyplannerEntities(string connexionStr)
            : base(connexionStr)
        {
        }

        public static bd_easyplannerEntities OpenWithFallback()
        {
            bd_easyplannerEntities bd = new bd_easyplannerEntities("name=bd_easyplannerEntities");
            try
            {
                bd.Database.Connection.Open();
            }
            catch
            {
                bd = new bd_easyplannerEntities("name=bd_easyplannerEntitiesFB");
                try
                {
                    bd.Database.Connection.Open();
                }
                catch
                {
                    return null;
                }
            }
            return bd;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AbsenceDemand> AbsenceDemands { get; set; }
        public DbSet<AbsencePreference> AbsencePreferences { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<ScheduleSlot> ScheduleSlots { get; set; }
        public DbSet<WorkingShift> WorkingShifts { get; set; }
    }
}
