//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleSlot
    {
        public int idTimeSlot { get; set; }
        public string dayOfWeek { get; set; }
        public System.TimeSpan startHour { get; set; }
        public Nullable<System.TimeSpan> endHour { get; set; }
        public Nullable<System.DateTime> firstDay { get; set; }
        public Nullable<System.DateTime> lastDay { get; set; }
        public int minAttendency { get; set; }
        public double DeltaTime
        {
            get
            {
                return this.endHour.Subtract(this.startHour).TotalHours;
            }
        }
    }
}
