//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingShift
    {
        public int idShift { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public string description { get; set; }
        public int idPerson { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
